services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: desafio_fullstack
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - reto-network

  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - reto-network

volumes:
  postgres_data:

networks:
  reto-network:
    external: true